# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Proofn™ email helps you convey your exact thoughts
email: agustiawanian@myabuy.com
description: > # this means to ignore newlines until "baseurl:"
  Proofn is an email platform where users can quickly change email-style they send to the recipient(s) regardless of reason. 
  Proofn provides an unlimited number of do-overs; 
  the sender can build stronger connections regardless of the recipient(s) disposition or background.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.proofn.com" # the base hostname & protocol for your site
twitter_username: tersenyum
github_username:  jekyll

# Build settings
markdown: kramdown
